
# Background
background {
    monitor =
    color = rgba(0, 0, 0, 1.0)
}

# Input field
input-field {
    monitor =
    size = 300, 50
    outline_thickness = 2
    dots_size = 0.2
    dots_spacing = 0.35
    outer_color = rgba(200, 200, 200, 0)
    inner_color = rgba(0, 0, 0, 0.5)
    font_color = rgb(200, 200, 200)
    fade_on_empty = false
    placeholder_text = <span foreground="##cdd6f4">Password...</span>
    
    position = 0, -120
    halign = center
    valign = center
}

# Time
label {
    monitor =
    text = cmd[update:1000] echo "$(date +"%H:%M")"
    font_size = 120
    font_family = JetBrains Mono
    color = rgba(200, 200, 200, 1.0)
    
    position = 0, 80
    halign = center
    valign = center
}

# Date
label {
    monitor =
    text = cmd[update:1000] echo "$(date +"%A, %B %d")"
    font_size = 24
    font_family = JetBrains Mono
    color = rgba(200, 200, 200, 1.0)
    
    position = 0, 0
    halign = center
    valign = center
}
